### ISSUE TITLE
Release build?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [wouterdebruijn/frigate-app#1]
So? any bluid for download?

**Comment by wouterdebruijn** [comment]
This project has been inactive since I found some limitations and issues with the available video streams supported by the native players. I was able to get WebRTC working, but it still that some stutter issues.

Since Frigate 0.14, the web dashboard is installable as PWA (Progressive web app), which covers most of my use-cases, making the need for this project less urgent.

**Comment by AnonymousWebHacker** [comment]
Frigate's UI is great, very modern, but at least in my experience, it seems very heavy or slow. And no, it is not because of my server or cell phone or network resources.

As for your problems, I assume you are referring to the ability to reproduce the frames , Exoplayer for Video H264 , MPV for H265 they are your friends.

The official frigate UI doesn't fit my needs at least. I have a server with 24-hour recordings, without object detection, and the UI is of no use to me with so many options for objects, detection, etc., when the only thing you want to see is the disk recordings and the live version.
